name: Dart

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "dart setup"
        uses: dart-lang/setup-dart@v1
      - name: "setup dart"
        run: |
          dart pub global activate dart_frog_cli
          dart_frog build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: posthellocode
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: ./build
          push: true
          tags: posthellocode/budgetizer:latest
      - name: Deploy on render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK}}
        run: curl $RENDER_DEPLOY_HOOK
