name: Dart

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub global activate dart_frog_cli
      - run: dart_frog build
      - run: cd build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: posthellocode
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: posthellocode/budgetizer:latest
